### PR TITLE
Tiny js world with oop

### PR DESCRIPTION
**Pull request by ThePickwickPapers**
_Replace task name and links as appropriate and remove this line._

### A  Tiny JS World with OOP

[Demo](https://thepickwickpapers.github.io/oop_exercise/) |
[Code base](https://github.com/ThePickwickPapers/frontend-2019-p2p/blob/tiny-js-world-with-oop/submissions/katyamykhailik/oop_exercise/index.js)

The code is submitted in its own sub-directory and in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@ThePickwickPapers thank you for your submission.
Did you do this task as a part of kottans/frontend course?

**Comment by OleksiyRudenko** [comment]
Oh, I see, you did. Please, hold on.

**Comment by OleksiyRudenko** [comment]
@ThePickwickPapers you have submitted your code for review to https://github.com/kottans/frontend-2019-p2p

Now you need to request mentors for review as described  [here](https://github.com/kottans/frontend-2019-p2p/blob/master/CONTRIBUTING.md) if not yet. Basically the same way as you did for CSS HTML Popup talk.

This repo accepts PRs to `worlds.md` as described in its `README.md`.

Should you require any further clarifications, please, do not hesitate asking.

**Comment by ThePickwickPapers** [comment]
@OleksiyRudenko  I have already posted a message in the Kottans Students Chat. Should I wait for someones review now? Thanks.

**Comment by OleksiyRudenko** [comment]
@ThePickwickPapers Questionnarium is a better place for this. General Students' is too chatty. 

I am choosing this PR for irrelevance.
Once you have your code reviewed, please, submit changes to worlds.md.

**Comment by OleksiyRudenko** [comment]
@ThePickwickPapers My apologies. This was my terrible mistake. Please, re-submit your PR.

**Pull request closed without merging**
