### PR TITLE
HTML-CSS-Popup

### PR DESCRIPTION
**Pull request by NickoKlevanski**
### HTML-CSS-Popup

[Demo](https://nickoklevanski.github.io/html-css-popup/) |
[Code base](https://github.com/NickoKlevanski/html-css-popup/tree/master/src)

The code is submitted in its own sub-directory and in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by aymkin** [comment]
1. There is no border for popup container (not visible enough)
boreder for popup

2. Focus on the icon should be presented while clicking on it
focus

3. Other google services
other goofgle services 

4. Set Favicon and title
Set Favicon and title

**Comment by NickoKlevanski** [comment]
@aymkin Please checkout)

**Comment by aymkin** [comment]
In the task [description](https://github.com/kottans/frontend/blob/master/tasks/html-css-popup.md) shown a triangle on top of the popup.
trangle

Can you make it?

**Comment by aymkin** [comment]
According to the task, the focus state should have a border (outline) around an icon, without text description.
Example:
example
Your way:
yours

**Comment by NickoKlevanski** [comment]
> In the task [description](https://github.com/kottans/frontend/blob/master/tasks/html-css-popup.md) shown a triangle on top of the popup.
> trangle
> 
> Can you make it?
@aymkin 
Hmmm. He is present in my popup.
What kind of OS and browser do you use?
joxi_screenshot_1554188818467

**Comment by aymkin** [comment]
1. My OS is LinuxMint
2.Now I see the triangle, I just could not find it due to: a) my poor eyesight b) triangle does not have box-shadow
no shdow

**Comment by aymkin** [comment]
You use multiple images for icons. Probably would be better to use CSS Sprites, which combines many small images in one big and use only ONE HTTP request to load the image. Plese, learn about that and try to use on the next project.
sprite

**Comment by A-Ostrovnyy** [comment]
Outline around icon(without text) it doesn't matter.
Your popup icon, bell icon, and avatar icon not accessible from the keyboard. Please fix it. Also, add styles to button More on `:hover` state.

**Comment by aymkin** [comment]
Please fix the mentioned improvements and you are good to go to ask for a pull request. 

P.S. Please, have a look at my [PR](https://github.com/kottans/frontend-2019-p2p/pull/58) and make visual and code review.

@A-Ostrovnyy could you be so kind and review PR #58 ?

**Pull request closed without merging**
